[package]
name = "dual_quaternion"
version = "0.1.0"
authors = ["HamaguRe <space-denpa.jp>"]
edition = "2018"

[dependencies]
dual_number = {git = "https://github.com/HamaguRe/dual_number.git", rev = "ee00d900ff6fa957bb6a729e4c3a532ac0430110"}
quaternion = {git = "https://github.com/HamaguRe/quaternion.git", rev = "022f3f24e369dabe5e7ef43e72a2605495341096"}